<a href="https://colab.research.google.com/github/ArrogantNobody/Pytorch_study/blob/main/1_tensor_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [3]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[1.5724e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.4145e-36]])


创建一个随机初始化的矩阵:



In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2290, 0.4000, 0.6893],
        [0.5851, 0.4852, 0.6365],
        [0.7318, 0.5469, 0.1785],
        [0.0668, 0.9214, 0.8821],
        [0.0112, 0.4482, 0.2763]])


创建一个0填充的矩阵，数据类型为long:



In [18]:
y = torch.zeros(x.shape, dtype=torch.long)
print(y)
y = torch.zeros_like(x)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


创建tensor并使用现有数据初始化:



In [13]:
x = torch.tensor([6.9, 3])
print(x)

tensor([6.9000, 3.0000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [15]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2347, -0.0876,  0.8156],
        [ 0.1734,  1.0654,  2.3028],
        [-0.8833, -1.4230,  0.6057],
        [-0.9427,  0.8463,  0.4759],
        [-1.6284,  1.3946, -0.0852]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [19]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [20]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 0.4775,  0.5573,  1.6824],
        [ 0.7376,  1.2572,  3.1934],
        [-0.0463, -1.1959,  0.8428],
        [ 0.0172,  1.4428,  1.2709],
        [-0.7631,  1.4210,  0.0760]])


加法2


In [21]:
print(torch.add(x, y))

tensor([[ 0.4775,  0.5573,  1.6824],
        [ 0.7376,  1.2572,  3.1934],
        [-0.0463, -1.1959,  0.8428],
        [ 0.0172,  1.4428,  1.2709],
        [-0.7631,  1.4210,  0.0760]])


提供输出tensor作为参数



In [22]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 0.4775,  0.5573,  1.6824],
        [ 0.7376,  1.2572,  3.1934],
        [-0.0463, -1.1959,  0.8428],
        [ 0.0172,  1.4428,  1.2709],
        [-0.7631,  1.4210,  0.0760]])


替换



In [23]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 0.4775,  0.5573,  1.6824],
        [ 0.7376,  1.2572,  3.1934],
        [-0.0463, -1.1959,  0.8428],
        [ 0.0172,  1.4428,  1.2709],
        [-0.7631,  1.4210,  0.0760]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [24]:
print(x)
print(x[:, 1])

tensor([[ 0.2347, -0.0876,  0.8156],
        [ 0.1734,  1.0654,  2.3028],
        [-0.8833, -1.4230,  0.6057],
        [-0.9427,  0.8463,  0.4759],
        [-1.6284,  1.3946, -0.0852]])
tensor([-0.0876,  1.0654, -1.4230,  0.8463,  1.3946])


``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [7]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断,总维度除以另一维度
print(x.size(), y.size(), z.size())
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 0.6785, -1.4424, -0.6933, -0.3559, -0.4031,  0.0981, -0.0667,  0.3641],
        [ 1.1069, -0.4504,  1.2094,  0.1160, -0.2887, -1.7597,  0.0738, -0.0562]])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [28]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.data)

tensor([0.3699])
0.3699162006378174
tensor([0.3699])


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组



In [29]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [31]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [32]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化



In [5]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [9]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
    print(z.cpu())

tensor([[ 1.6785, -0.4424,  0.3067,  0.6441],
        [ 0.5969,  1.0981,  0.9333,  1.3641],
        [ 2.1069,  0.5496,  2.2094,  1.1160],
        [ 0.7113, -0.7597,  1.0738,  0.9438]], device='cuda:0')
tensor([[ 1.6785, -0.4424,  0.3067,  0.6441],
        [ 0.5969,  1.0981,  0.9333,  1.3641],
        [ 2.1069,  0.5496,  2.2094,  1.1160],
        [ 0.7113, -0.7597,  1.0738,  0.9438]], dtype=torch.float64)
tensor([[ 1.6785, -0.4424,  0.3067,  0.6441],
        [ 0.5969,  1.0981,  0.9333,  1.3641],
        [ 2.1069,  0.5496,  2.2094,  1.1160],
        [ 0.7113, -0.7597,  1.0738,  0.9438]])
